FROM nginx
MAINTAINER qiqiangvae@foxmail.com
WORKDIR ./src/ipoem-h5
# h5 文件
# ADD ./src/ipoem-h5/dist/ /home/nginx/ipoem-h5
# nginx配置
# ADD ./nginx/nginx.conf /etc/nginx/nginx.conf
CMD ["nginx","-c","/etc/nginx/nginx.conf","-g","daemon off;"]

EXPOSE 7071

